steps:
  # Step 0: Create .env.production file
  - name: ubuntu
    args:
      - '-c'
      - |
        set -e

        cat > .env.production <<EOF

        NEXT_PUBLIC_API_BASE_URL=https://api.tooryst.co/api/v1

        NEXT_PUBLIC_APP_URL=https://staging.tooryst.co

        NEXT_PUBLIC_APP_NAME=Tooryst

        NEXT_PUBLIC_API_TIMEOUT=30000

        NEXT_PUBLIC_REVALIDATE_SECONDS=300

        NEXT_PUBLIC_COMPANY_NAME=Tooryst

        NEXT_PUBLIC_COMPANY_DESCRIPTION=Discover the best times to visit your
        favorite attractions. Get real-time crowd levels and plan your perfect
        visit.

        NEXT_PUBLIC_COMPANY_TAGLINE=Your Guide to Unforgettable Destinations

        NEXT_PUBLIC_COMPANY_FOUNDED=2024

        NEXT_PUBLIC_CONTACT_EMAIL=travel@thebettervacation.com

        NEXT_PUBLIC_SUPPORT_EMAIL=travel@thebettervacation.com

        NEXT_PUBLIC_PHONE_NUMBER=+91 73588-08488

        NEXT_PUBLIC_OFFICE_ADDRESS=Firestorm Internet, 203, 30C, Bollineni
        Hillside, Perumbakkam Main Road, Nookampalayam, Chennai, India – 600126

        NEXT_PUBLIC_SOCIAL_TWITTER=https://twitter.com/bettervacation_

        NEXT_PUBLIC_SOCIAL_LINKEDIN=https://www.linkedin.com/company/thebettervacation/

        NEXT_PUBLIC_SOCIAL_PINTEREST=https://www.pinterest.com/thebettervacation/

        NEXT_PUBLIC_SOCIAL_FACEBOOK=https://www.facebook.com/thebettervacation

        NEXT_PUBLIC_SOCIAL_INSTAGRAM=https://www.instagram.com/thebettervacation/

        NEXT_PUBLIC_SOCIAL_YOUTUBE=https://www.youtube.com/channel/UCmSy2vAcpu2ULN0tHV6aA1A

        NEXT_PUBLIC_STAT_DESTINATIONS=45

        NEXT_PUBLIC_STAT_ATTRACTIONS=966

        NEXT_PUBLIC_STAT_REVIEWS=46000

        NEXT_PUBLIC_STAT_USERS=125000

        NEXT_PUBLIC_FAQ_COUNT=8

        NEXT_PUBLIC_COMPANY_WEBSITE=https://tooryst.co

        NEXT_PUBLIC_PRIVACY_POLICY_URL=/privacy-policy

        NEXT_PUBLIC_TERMS_OF_SERVICE_URL=/terms-of-service

        NEXT_PUBLIC_COOKIE_POLICY_URL=/cookie-policy

        NEXT_PUBLIC_DEFAULT_META_DESCRIPTION=Discover and explore attractions
        worldwide with authentic travel insights from our community

        NEXT_PUBLIC_SITE_NAME=Tooryst

        NEXT_PUBLIC_BRAND_COLOR=#3B82F6

        NEXT_PUBLIC_ENABLE_CONTACT_FORM=false

        NEXT_PUBLIC_ENABLE_NEWSLETTER=false

        NEXT_PUBLIC_ENABLE_AUTH=false

        NEXT_PUBLIC_ENABLE_BLOG=false

        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$$GOOGLE_MAPS_API_KEY

        NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID=1ddb8b2b125e4212a9964914

        NEXT_PUBLIC_MAPBOX_TOKEN=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw

        NEXT_PUBLIC_FALLBACK_ATTRACTION_IMAGE=/images/fallbacks/attraction-fallback.jpg

        NEXT_PUBLIC_FALLBACK_CITY_IMAGE=/images/fallbacks/city-fallback.jpg

        NEXT_PUBLIC_FALLBACK_HERO_IMAGE=/images/fallbacks/hero-fallback.jpg

        NEXT_PUBLIC_SEARCH_PAGE_SIZE=12

        NEXT_PUBLIC_CITIES_FETCH_LIMIT=100

        NEXT_PUBLIC_ATTRACTIONS_FETCH_LIMIT=12

        NEXT_PUBLIC_COUNTRY_DATA_LIMIT=1000

        NEXT_PUBLIC_MAP_DEFAULT_ZOOM=13

        NEXT_PUBLIC_MAP_BOUNDS_PADDING_TOP=50

        NEXT_PUBLIC_MAP_BOUNDS_PADDING_RIGHT=50

        NEXT_PUBLIC_MAP_BOUNDS_PADDING_BOTTOM=50

        NEXT_PUBLIC_MAP_BOUNDS_PADDING_LEFT=50

        NEXT_PUBLIC_MAP_RETRY_LIMIT=2

        NEXT_PUBLIC_COLLAGE_IMAGE_LIMIT=6

        NEXT_PUBLIC_SEARCH_SUGGESTION_LIMIT=5

        NEXT_PUBLIC_DEBOUNCE_MS=300

        NEXT_PUBLIC_RATING_DECIMAL_PLACES=1

        NEXT_PUBLIC_DEFAULT_BACKGROUND=linear-gradient(120deg,
        rgba(37,99,235,0.85), rgba(147,51,234,0.85))

        NEXT_PUBLIC_HERO_OVERLAY=linear-gradient(120deg, rgba(15,23,42,0.7),
        rgba(15,23,42,0.4))

        NEXT_PUBLIC_GA_ID=G-CW2LJ9QCNN

        NEXT_PUBLIC_HOTJAR_ID=

        NEXT_PUBLIC_ENVIRONMENT=staging

        NEXT_PUBLIC_APP_VERSION=1.0.0

        NEXT_PUBLIC_MAINTENANCE_MODE=false

        NEXT_PUBLIC_MAINTENANCE_MESSAGE=We are currently performing scheduled
        maintenance. Please check back soon!

        NEXT_PUBLIC_SEARCH_TITLE=Search Tooryst

        NEXT_PUBLIC_SEARCH_PLACEHOLDER=Search cities or attractions

        NEXT_PUBLIC_SEARCH_BUTTON=Search

        NEXT_PUBLIC_SEARCH_LOADING=Searching…

        NEXT_PUBLIC_SEARCH_NO_RESULTS=No results found. Try a different search
        term or explore popular cities.

        NEXT_PUBLIC_SEARCH_EMPTY_STATE=No cities or attractions available. Try
        searching for a specific city or attraction.

        NEXT_PUBLIC_SEARCH_ERROR=Something went wrong. Try again.

        NEXT_PUBLIC_FILTER_CITIES=Cities

        NEXT_PUBLIC_FILTER_ATTRACTIONS=Attractions

        NEXT_PUBLIC_CITY_CARD_ATTRACTIONS_LABEL=attractions

        NEXT_PUBLIC_CITY_CARD_VIEW_BUTTON=View city guide →

        NEXT_PUBLIC_SECTION_CITIES_HEADER=Cities

        NEXT_PUBLIC_SECTION_ATTRACTIONS_HEADER=Attractions

        NEXT_PUBLIC_TRENDING_EYEBROW=Trending Now

        NEXT_PUBLIC_TRENDING_HEADING=Live attraction signals

        NEXT_PUBLIC_TRENDING_SUBHEADING=Based on real visitor demand, crowd
        comfort, and seasonal weather.

        NEXT_PUBLIC_TRENDING_EMPTY=No trending attractions available yet.

        NEXT_PUBLIC_CITIES_EYEBROW=Explore

        NEXT_PUBLIC_CITIES_HEADING=Popular Cities

        NEXT_PUBLIC_CITIES_SEE_ALL=See all cities →

        NEXT_PUBLIC_CITIES_EMPTY=No cities available yet.

        NEXT_PUBLIC_GLOBE_EYEBROW=Global

        NEXT_PUBLIC_GLOBE_HEADING=Explore the World

        NEXT_PUBLIC_GLOBE_VIEW_CITY=View City →

        NEXT_PUBLIC_NEWSLETTER_EYEBROW=Stay in the loop

        NEXT_PUBLIC_NEWSLETTER_HEADING=Get next-week travel intel

        NEXT_PUBLIC_NEWSLETTER_SUBHEADING=Weekly guidance on crowd comfort,
        ideal itineraries, and under-the-radar cities.

        NEXT_PUBLIC_NEWSLETTER_PLACEHOLDER=you@example.com

        NEXT_PUBLIC_NEWSLETTER_BUTTON=Get travel intel

        NEXT_PUBLIC_EMPTY_STATE_HEADING=No Data Available

        NEXT_PUBLIC_EMPTY_STATE_MESSAGE=The database is empty. Import
        attractions data to get started with your travel storyboard.

        NEXT_PUBLIC_EMPTY_STATE_SETUP_TITLE=Setup Instructions

        NEXT_PUBLIC_LOADING_GLOBE=Loading globe...

        NEXT_PUBLIC_LOADING_RESULTS=Loading results…

        NEXT_PUBLIC_PAGINATION_PREVIOUS=Previous

        NEXT_PUBLIC_PAGINATION_NEXT=Next

        NEXT_PUBLIC_PAGINATION_PAGE=Page

        NEXT_PUBLIC_ACTION_VIEW=View

        NEXT_PUBLIC_ACTION_EXPLORE=Explore

        NEXT_PUBLIC_ACTION_SEARCH=Search

        NEXT_PUBLIC_ACTION_FILTER=Filter

        NEXT_PUBLIC_SENTRY_DSN=https://8ffe2c57fa82a5110ffb4dc1483f7175@o4510596311547904.ingest.us.sentry.io/4510596912185344

        NEXT_PUBLIC_SENTRY_ENVIRONMENT=staging

        NEXT_PUBLIC_SENTRY_ENABLED=true

        NEXT_PUBLIC_SENTRY_TRACES_SAMPLE_RATE=1.0

        NEXT_PUBLIC_SENTRY_REPLAYS_SESSION_SAMPLE_RATE=0.1

        NEXT_PUBLIC_SENTRY_REPLAYS_ON_ERROR_SAMPLE_RATE=1.0

        EOF


        echo "✓ Created .env.production file"

        cat .env.production
    entrypoint: bash
    secretEnv:
      - GOOGLE_MAPS_API_KEY

  # Step 1: Build Docker image with proper error handling
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - |
        set -e  # Exit immediately if any command fails
        set -o pipefail  # Catch errors in pipes

        echo "Starting Docker build..."

        docker build \
          --build-arg SENTRY_AUTH_TOKEN="$$SENTRY_AUTH_TOKEN" \
          --build-arg NEXT_PUBLIC_GOOGLE_MAPS_API_KEY="$$GOOGLE_MAPS_API_KEY" \
          --build-arg NEXT_PUBLIC_GOOGLE_MAPS_MAP_ID="1ddb8b2b125e4212a9964914" \
          --build-arg NEXT_PUBLIC_API_BASE_URL="https://api.tooryst.co/api/v1" \
          --build-arg NEXT_PUBLIC_APP_URL="https://tooryst.co" \
          --build-arg NEXT_PUBLIC_ENVIRONMENT="staging" \
          --build-arg NEXT_PUBLIC_SENTRY_DSN="https://8ffe2c57fa82a5110ffb4dc1483f7175@o4510596311547904.ingest.us.sentry.io/4510596912185344" \
          --build-arg NEXT_PUBLIC_SENTRY_ENVIRONMENT="staging" \
          -t us-central1-docker.pkg.dev/toorists/tooryst-repo-frontend/frontend-staging:$SHORT_SHA \
          -t us-central1-docker.pkg.dev/toorists/tooryst-repo-frontend/frontend-staging:latest \
          . || {
            echo "ERROR: Docker build failed!"
            exit 1
          }

        echo "✓ Docker build completed successfully"

        # Verify image was created
        docker images | grep us-central1-docker.pkg.dev/toorists/tooryst-repo-frontend/frontend || {
          echo "ERROR: Docker image not found after build!"
          exit 1
        }
    entrypoint: bash
    secretEnv:
      - SENTRY_AUTH_TOKEN
      - GOOGLE_MAPS_API_KEY

  # Step 2: Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - us-central1-docker.pkg.dev/toorists/tooryst-repo-frontend/frontend-staging

  # Step 3: Deploy to Cloud Run (staging)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - deploy
      - tooryst-frontend-staging
      - '--image'
      - >-
        us-central1-docker.pkg.dev/toorists/tooryst-repo-frontend/frontend-staging:$SHORT_SHA
      - '--region'
      - us-central1
      - '--platform'
      - managed
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - 1Gi
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '5'
      - '--set-env-vars'
      - NODE_ENV=production
    entrypoint: gcloud

  # Step 4: Ensure unauthenticated access (fix for IAM race condition)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - add-iam-policy-binding
      - tooryst-frontend-staging
      - '--region'
      - us-central1
      - '--member'
      - allUsers
      - '--role'
      - roles/run.invoker
    entrypoint: gcloud

images:
  - >-
    us-central1-docker.pkg.dev/toorists/tooryst-repo-frontend/frontend-staging:$SHORT_SHA
  - 'us-central1-docker.pkg.dev/toorists/tooryst-repo-frontend/frontend-staging:latest'

options:
  machineType: E2_HIGHCPU_8
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/toorists/secrets/tooryst_google_maps_api_key/versions/latest
      env: GOOGLE_MAPS_API_KEY
    - versionName: projects/toorists/secrets/tooryst_sentry_auth_token/versions/latest
      env: SENTRY_AUTH_TOKEN
